// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvbghkchpzpekzxlruqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2Ymdoa2NocHpwZWt6eGxydXF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNTU0ODksImV4cCI6MjA2NDkzMTQ4OX0.UuEdTTpCHthelVj9OZJ93UfLCUyZ1ZTMAXIx4Y6zGGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);